### ISSUE TITLE
Problems with recommended library

### ISSUE THREAD

**Issue by gloglas** [joelsernamoreno/EvilCrow-Cable#1]
Hi, I installed advised [library](https://github.com/ernesto-xload/DigisparkKeyboard).
And I've tried many layouts but every single one typed out gibberish and println didn't make a newline afterwards.
I know It it is not exactly *your* issue but if you do not install it, you can use the in-built one in `...ppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.7\libraries\DigisparkKeyboard` and that one will work. (of course with no layout options).

**Comment by joelsernamoreno** [comment]
Hello!
You mean the keymap in another language? Example: special characters @!¡¿;...

I don't like Windows, I use Linux.

But... I think that the DigiKeyboard library has to be in Documents/Arduino/libraries directory

You have to edit the library configuration file and put the keymap of your country (you have to edit this in the DigiKeyboard.h file, in the latest versions of Arduino you can't modify this in the sketch .ino)

I hope to answer your question, my English is very bad and I may not have answered correctly

If I haven't answered correctly, explain your question better and I can help you :D

**Comment by gloglas** [comment]
I know exactly what you mean.

The library is correctly placed.

I edited (defined) the country in DigiKeyboard.h. But the layout array is weird. Instead of powershell it types for example something like this `dacogsobb`. But If I tried the original bulit-in library. The scancode-ascii-table.h works just fine. But when I replace that with "digi_cz_cz.h", it types out same thing.

**Comment by joelsernamoreno** [comment]
Now I understand this.

If... I can't say that all the layout work properly. I use the ES layout and it works

You can modify the library and add the correct layout for your keyboard

You can make a Pull Request for the library developer to add your change :D

**Comment by gloglas** [comment]
Problem solved: https://github.com/ernesto-xload/DigisparkKeyboard/issues/5
